name: "Bobby's Blog"
description: "Thoughts on software, music and new business models"

author: "Bobby Matson"

url: "http://blog.bomatson.com"
baseurl: ""
image: "/assets/img/avatar.jpg"

permalink: :year/:month/:title.html
highlighter: rouge

# Google Analytics
# ga_domain: m3xm.github.io
ga_tracking_id: UA-102723673-1
