name: "Instrumental Tech"
description: "Instrumental Tech"

author: "Bobby Matson"

url: "http://blog.bomatson.com"
baseurl: ""

permalink: :year/:month/:title.html
highlighter: pygments

# Google Analytics
# ga_domain: m3xm.github.io
#ga_tracking_id: UA-47727049-1
